In [1]:
# manual hyperparameter tuning is here! production ready!
!pip install quick-sentiments==0.6.4

Collecting quick-sentiments==0.6.4
  Downloading quick_sentiments-0.6.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.23.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (2.4.3)
Requirement already satisfied: pandas>=2.0.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (3.0.1)
Requirement already satisfied: polars>=0.20.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (1.39.3)
Requirement already satisfied: scipy>=1.9.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (1.17.1)
Requirement already satisfied: scikit-learn>=1.3.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (1.8.0)
Requirement already satisfied: xgboost>=2.0.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (3.2.0)
Requirement already satisfied: gensim>=4.3.3 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (4.4.0)
Requirement already satisfied: nltk==3.8.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (3.8.1)
Requirement already satisfied: spacy>=3.0.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.6.4) (3.8.11)
Requirement already satisfied: click in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.6.4) (8.3.1)
Requirement already satisfied: joblib in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.6.4) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.6.4) (2026.2.28)
Requirement already satisfied: tqdm in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.6.4) (4.67.3)
Requirement already satisfied: smart_open>=1.8.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from gensim>=4.3.3->quick-sentiments==0.6.4) (7.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick-sentiments==0.6.4) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick-sentiments==0.6.4) (2025.3)
Requirement already satisfied: polars-runtime-32==1.39.3 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from polars>=0.20.0->quick-sentiments==0.6.4) (1.39.3)
Requirement already satisfied: six>=1.5 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->quick-sentiments==0.6.4) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from scikit-learn>=1.3.0->quick-sentiments==0.6.4) (3.6.0)
Requirement already satisfied: wrapt in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from smart_open>=1.8.1->gensim>=4.3.3->quick-sentiments==0.6.4) (2.1.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (8.3.11)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (2.12.5)
Requirement already satisfied: jinja2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (80.10.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.6.4) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.6.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.6.4) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.6.4) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.6.4) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.6.4) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.6.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.6.4) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.6.4) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick-sentiments==0.6.4) (1.3.3)
Requirement already satisfied: confection<1.1.0,>=0.0.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick-sentiments==0.6.4) (0.1.5)
Requirement already satisfied: colorama in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from tqdm->nltk==3.8.1->quick-sentiments==0.6.4) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy>=3.0.0->quick-sentiments==0.6.4) (0.23.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.6.4) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from jinja2->spacy>=3.0.0->quick-sentiments==0.6.4) (3.0.3)
Downloading quick_sentiments-0.6.4-py3-none-any.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ----------------------------------- ---- 2.4/2.6 MB 13.8 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 12.1 MB/s  0:00:00
Installing collected packages: quick-sentiments
  Attempting uninstall: quick-sentiments
    Found existing installation: quick-sentiments 0.6.3
    Uninstalling quick-sentiments-0.6.3:
      Successfully uninstalled quick-sentiments-0.6.3
Successfully installed quick-sentiments-0.6.4

In [2]:
!pip show quick_sentiments #check for latest version

Name: quick-sentiments
Version: 0.6.4
Summary: Sentiment Analysis pipeline
Home-page: https://github.com/AlabhyaMe/Sentiments-Analysis
Author: Alabhya Dahal
Author-email: Alabhya Dahal <alabhya.dahal@gmail.com>
License: MIT License
Location: C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages
Requires: gensim, nltk, numpy, pandas, polars, scikit-learn, scipy, spacy, xgboost
Required-by:

WARNING: Package(s) not found: #check, for, latest, version

In [3]:
import polars as pl

# here I have three python script I built to pre_process the data and running the pipeline
# you can find the code in the tools/preprocess.py file
# you can find  the code in the tools/pipeline.py file
# the pre_process function is used to clean the text data, there are various options available, please check the tools/preprocess.py file for details
# the run_pipeline function is used to run the sentimental analysis pipeline, it takes the training data and the vectorizer and machine learning methods as input, and returns the results
from quick_sentiments import pre_process_nltk
from quick_sentiments import pre_process_spacy
from quick_sentiments import run_pipeline
from quick_sentiments import make_predictions
from quick_sentiments import evaluate_performance

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\meala\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\meala\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

### Training Dataset

In [4]:
# this template uses csv files 
# column names can be set in Python but this template does not automatically update the column for the demo 
# however, the function will give you the option to tell column names for the text and label data

df_train = pl.read_csv("demo/training_data/train.csv",encoding='ISO-8859-1') 
print(f"Dataset shape: {df_train.shape[0]} rows and {df_train.shape[1]} columns")

Dataset shape: 162758 rows and 5 columns

### DEMO

In [5]:
df_train.head()
# randomly select only 10% of the data since the dataset is large
#RUN ONLY ONCE
df_train = df_train.sample(fraction=0.05, shuffle=True, seed=42) 
df_train.head(5)

shape: (5, 5)
┌───────────────────────┬──────────────────┬────────────────────┬──────────────────────┬───────────┐
│ movieid               ┆ reviewerName     ┆ isFrequentReviewer ┆ reviewText           ┆ sentiment │
│ ---                   ┆ ---              ┆ ---                ┆ ---                  ┆ ---       │
│ str                   ┆ str              ┆ bool               ┆ str                  ┆ str       │
╞═══════════════════════╪══════════════════╪════════════════════╪══════════════════════╪═══════════╡
│ don_vito_corleone_wil ┆ Jacob Hansen Jr. ┆ true               ┆ An acceptably        ┆ NEGATIVE  │
│ ly_wonka_…            ┆                  ┆                    ┆ mindless sanctua…    ┆           │
│ annie_hall_james_t._k ┆ Manuel Ramirez   ┆ false              ┆ Although many shots  ┆ POSITIVE  │
│ irk_hiccu…            ┆                  ┆                    ┆ are out of…          ┆           │
│ ellis_redding_legend_ ┆ Jose Mccormick   ┆ false              ┆ null                 ┆ NEGATIVE  │
│ forrest_g…            ┆                  ┆                    ┆                      ┆           │
│ infinite_gandalf_the_ ┆ Heidi Wood       ┆ false              ┆ 10 Cloverfield Lane  ┆ POSITIVE  │
│ grey                  ┆                  ┆                    ┆ is an exci…          ┆           │
│ katniss_everdeen_dart ┆ Nicholas Park    ┆ true               ┆ It's funny, fast,    ┆ POSITIVE  │
│ h_vader_n…            ┆                  ┆                    ┆ and charming…        ┆           │
└───────────────────────┴──────────────────┴────────────────────┴──────────────────────┴───────────┘

The dataset is for training. The sentiments are already labeled. This will allow us to train a model that can predict sentiments on new data.

In [6]:
# you can use the pre_process function to clean the text data
response_column = "reviewText" # this is the column name for the text data, feel free to change it to your text column name
sentiment_column = "sentiment" # this is the column name for the sentiment data, feel free to change it to your sentiment column name

In [7]:
# make changes as necessary
# inside the map_elements, add  the parameters [pre_process(x, parameters_to_be_added)] and set it True/False if it differs from the defualt value
# check the tools/preprocess.py file for the parameters and their default values
# some of the parameters are remove_brackets, remove_stopwords, remove_punctuation, remove_numbers, remove_emojis, remove_urls, remove_html_tags, lemmatize, stem, lowercase
df_train = pre_process_nltk(df_train, text_column=response_column, new_column_name="cleaned_text_nltk")

In [8]:
df_train = pre_process_spacy(df_train, text_column=response_column, new_column_name="cleaned_text_spacy")

In [9]:
df_train.head()

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬─────────────┬───────────┬─────────────┬─────────────┐
│ movieid      ┆ reviewerName ┆ isFrequentRe ┆ reviewText  ┆ sentiment ┆ cleaned_tex ┆ cleaned_tex │
│ ---          ┆ ---          ┆ viewer       ┆ ---         ┆ ---       ┆ t_nltk      ┆ t_spacy     │
│ str          ┆ str          ┆ ---          ┆ str         ┆ str       ┆ ---         ┆ ---         │
│              ┆              ┆ bool         ┆             ┆           ┆ str         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══════════╪═════════════╪═════════════╡
│ don_vito_cor ┆ Jacob Hansen ┆ true         ┆ An          ┆ NEGATIVE  ┆ an          ┆ an          │
│ leone_willy_ ┆ Jr.          ┆              ┆ acceptably  ┆           ┆ acceptably  ┆ acceptably  │
│ wonka_…      ┆              ┆              ┆ mindless    ┆           ┆ mindless    ┆ mindless    │
│              ┆              ┆              ┆ sanctua…    ┆           ┆ sanctua…    ┆ sanctua…    │
│ annie_hall_j ┆ Manuel       ┆ false        ┆ Although    ┆ POSITIVE  ┆ although    ┆ although    │
│ ames_t._kirk ┆ Ramirez      ┆              ┆ many shots  ┆           ┆ many shots  ┆ many shots  │
│ _hiccu…      ┆              ┆              ┆ are out of… ┆           ┆ are out of… ┆ are out of… │
│ ellis_reddin ┆ Jose         ┆ false        ┆ null        ┆ NEGATIVE  ┆             ┆             │
│ g_legend_for ┆ Mccormick    ┆              ┆             ┆           ┆             ┆             │
│ rest_g…      ┆              ┆              ┆             ┆           ┆             ┆             │
│ infinite_gan ┆ Heidi Wood   ┆ false        ┆ 10          ┆ POSITIVE  ┆ cloverfield ┆ cloverfield │
│ dalf_the_gre ┆              ┆              ┆ Cloverfield ┆           ┆ lane is an  ┆ lane is an  │
│ y            ┆              ┆              ┆ Lane is an  ┆           ┆ excitin…    ┆ excitin…    │
│              ┆              ┆              ┆ exci…       ┆           ┆             ┆             │
│ katniss_ever ┆ Nicholas     ┆ true         ┆ It's funny, ┆ POSITIVE  ┆ it s funny  ┆ it s funny  │
│ deen_darth_v ┆ Park         ┆              ┆ fast, and   ┆           ┆ fast and    ┆ fast and    │
│ ader_n…      ┆              ┆              ┆ charming…   ┆           ┆ charming    ┆ charming    │
└──────────────┴──────────────┴──────────────┴─────────────┴───────────┴─────────────┴─────────────┘

In [ ]:
#### 6 plus text representation / vectorizer methods available 
#### in the function run_pipeline (in python cell below), we shall make use of this, write the words inside [ ] for the methods you want to use
#### 1. Bag of Words [BOW] 
#### 2. Term Frequency [tf]
#### 3. TF -IDF    [tfidf]
#### 4. Word Embedding using Word2Vec (you can use other packages with slight changes) [wv] 
         # Word Embedding uses defualt 300 values; this will take some time to run
#### 5. Glove (you can use other packages with slight changes) [glove_25,glove_50, glove_100, gl0ve_200]
#### 6. Hugging Face Transformers (you can use other packages with slight changes) [transformer]. You have to download hugging face transformer models to use this method, check the tools/pipeline.py file for details

In [ ]:
#### 6 there are also five machine learning methods that can be used
#### 1. Logistic Regression [logit]
#### 2. Random forest (recommended) (rf)
#### 3. XGBoosting  [XGB](word embedding and XGBoost may take long time to complete, combination of both is not recommended in local machine)
#### 4. Naive Bayes [nb]
#### 5. Neural Network [nn] (this will take some time to run, and may run out of memory if the dataset is large, so be careful when using this method)
#### 6. Tensorflow/Keras [tf, tensorflow, keras] (this will take some time to run, and may run out of memory if the dataset is large, so be careful when using this method)

In [10]:
# example parameters for all
#Logit
custom_logit = {
    'C': [0.01, 0.1, 1.0, 10.0, 100.0],
    'solver': ['liblinear', 'lbfgs', 'saga'],
    'class_weight': [None, 'balanced'],
    'max_iter': [500, 1000, 2000]
}
#Random Forest
custom_rf = {
    'n_estimators': [100, 300, 500],
    'max_depth': [10, 20, 50, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False],
    'class_weight': [None, 'balanced', 'balanced_subsample']
}
#XGBoost
custom_xgb = {
    'n_estimators': [100, 300, 500],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2] # Minimum loss reduction required to make a further partition
}
#Neural Network
custom_nn = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01, 0.1],
    'learning_rate_init': [0.001, 0.01] 
}
#Tensorflow/Keras
custom_tf = {
    'model__hidden_units': [64, 128, 256],
    'model__dropout_rate': [0.2, 0.3, 0.5],
    'batch_size': [32, 64, 128],
    'epochs': [10, 20] 
}
#Naive Bayers Multinomial
custom_nb_multinomial = {
    'alpha': [0.001, 0.01, 0.1, 0.5, 1.0, 5.0, 10.0], # Smoothing parameter
    'fit_prior': [True, False]
}
#Naive Bayes Gaussian (If using Word2Vec, GloVe, or Hugging Face (Gaussian)
custom_nb_gaussian = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5] # Portion of the largest variance of all features
}

In [16]:
# this is the example of how to use the function
# you can change the vectorizer_name and model_name to the ones you want to use
# for now we will use word embedding and tensorflow
# write the name of your columns in the text_column_name and sentiment_column_name
# the text_column_name is the column name of the text data, and sentiment_column_name is

# run_pipeline function will return the dataframe with the vectorized text, vectorizer used  and the model
# it will also print the results of the model, including the accuracy and F1 score
# note, even without hyperparameter tuning, the model is getting over 70% accuracy in my test
# there may not be a need to perform hyperparameter tuning, but you can set perform_tuning to True if you want to do that
model = run_pipeline(
    # Primary parameters that are required
    vectorizer_name="BOW", # BOW, tf, tfidf, wv,  glove_25,glove_50, glove_100, gl0ve_200,
    model_name="logit", # logit, rf, XGB, nb, nn, tf for tensorflow models .#XGB takes long time, can not recommend using it on normal case
    df=df_train,
    text_column_name="cleaned_text_spacy",  # this is the column name of the text data, 
    sentiment_column_name = "sentiment",
    
    # Optional parameters, 
    perform_tuning = True, # make this true if you want to perform hyperparameter tuning, it will take longer time and 
    param_grid=custom_logit,
    interactive=False, 
    random_state=259
)

   - Interactive mode disabled. Fail-fast safety engaged.
--- Running Pipeline for Bow + Logit ---
1. Splitting data into train/test...
2. Vectorizing  dataset (X)...
   - Generating Bag-of-Words features...
   - Transforming test data using fitted Bag-of-Words vectorizer...
3. Training and predicting...
   - Starting Logistic Regression training with CUSTOM PARAMETER, GridSearchCV for hyperparameter tuning...
Fitting 5 folds for each of 90 candidates, totalling 450 fits

   - Best Hyperparameters found:
{'C': 1.0, 'class_weight': 'balanced', 'max_iter': 500, 'solver': 'lbfgs'}
   - Best Cross-Validation Score (F1-weighted): 0.7202

Best model parameters: {'C': 1.0, 'class_weight': 'balanced', 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': 0.0, 'max_iter': 500, 'n_jobs': None, 'penalty': 'deprecated', 'random_state': 259, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
4. Evaluating model...

Classification Report:
              precision    recall  f1-score   support

    NEGATIVE       0.58      0.60      0.59       536
    POSITIVE       0.80      0.79      0.79      1092

    accuracy                           0.73      1628
   macro avg       0.69      0.69      0.69      1628
weighted avg       0.73      0.73      0.73      1628

True labels distribution: Counter({np.int64(1): 1092, np.int64(0): 536})
Predicted labels distribution: Counter({np.int64(1): 1077, np.int64(0): 551})

In [17]:
evaluate_performance(model["y_test"], model["y_prob_matrix"][:, 1],positive_label=1) #alphanumeric labels, 0 is negative, 1 is positive in this case, change it as necessary

{'best_roc_threshold': np.float64(0.6242),
 'best_pr_threshold': np.float64(0.2545),
 'decile_table':     Threshold  Accuracy  Precision  Recall     F1
 0         0.0     0.671      0.671   1.000  0.803
 1         0.1     0.703      0.700   0.976  0.815
 2         0.2     0.719      0.722   0.944  0.819
 3         0.3     0.728      0.749   0.893  0.815
 4         0.4     0.733      0.777   0.845  0.810
 5         0.5     0.727      0.800   0.789  0.795
 6         0.6     0.697      0.842   0.675  0.749
 7         0.7     0.660      0.867   0.583  0.697
 8         0.8     0.623      0.909   0.486  0.634
 9         0.9     0.527      0.926   0.321  0.476
 10        1.0     0.329      0.000   0.000  0.000}

In [20]:
evaluate_performance(model["y_test"], model["y_prob_matrix"][:, 0],positive_label=0) # negative label as reference, change it as necessary

{'best_roc_threshold': np.float64(0.3778),
 'best_pr_threshold': np.float64(0.3778),
 'decile_table':     Threshold  Accuracy  Precision  Recall     F1
 0         0.0     0.329      0.329   1.000  0.495
 1         0.1     0.527      0.406   0.948  0.569
 2         0.2     0.623      0.463   0.901  0.611
 3         0.3     0.660      0.490   0.817  0.613
 4         0.4     0.697      0.529   0.743  0.618
 5         0.5     0.727      0.583   0.599  0.591
 6         0.6     0.733      0.616   0.506  0.555
 7         0.7     0.728      0.642   0.392  0.487
 8         0.8     0.719      0.697   0.261  0.380
 9         0.9     0.703      0.752   0.147  0.246
 10        1.0     0.671      0.000   0.000  0.000}

In [21]:
## the model is a dictionary that contains the results of the model, including the accuracy and F1 score

# you can access the results using the keys of the dictionary
print("Vectorizer used: ", model["vectorizer_name"])
print("Model used: ", model["model_object"])
print("Accuracy: ", model["accuracy"])

Vectorizer used:  BOW
Model used:  LogisticRegression(class_weight='balanced', max_iter=500, random_state=259)
Accuracy:  0.7266584766584766

### New Dataset for prediction
You can use the same format as the training dataset, but ensure that it contains the "Response" column for text data. The "Sentiment" column is optional for prediction datasets, as it will be generated by the model.
Make sure the dataset is saved in the "New Data" folder and is in CSV format.

In [22]:
new_data = pl.read_csv("demo/new_data/test.csv",encoding='ISO-8859-1') #keep your file here
print(new_data.shape)
new_data= new_data.sample(fraction=0.25, shuffle=True, seed=42)
print(new_data.shape)

(55315, 4)
(13828, 4)

In [23]:
new_data = pre_process_nltk(new_data, text_column=response_column, new_column_name="cleaned_text")
new_data.head()

shape: (5, 5)
┌──────────────────────┬───────────────┬─────────────┬──────────────────────┬──────────────────────┐
│ movieid              ┆ reviewerName  ┆ isTopCritic ┆ reviewText           ┆ cleaned_text         │
│ ---                  ┆ ---           ┆ ---         ┆ ---                  ┆ ---                  │
│ str                  ┆ str           ┆ bool        ┆ str                  ┆ str                  │
╞══════════════════════╪═══════════════╪═════════════╪══════════════════════╪══════════════════════╡
│ spectacular_whirlwin ┆ Craig Lambert ┆ false       ┆ Cranston commands    ┆ cranston commands    │
│ d_dazzling…          ┆               ┆             ┆ the screen, …        ┆ the screen b…        │
│ astonish_katniss_eve ┆ Sara French   ┆ true        ┆ All good stuff. Rock ┆ all good stuff rock  │
│ rdeen_myri…          ┆               ┆             ┆ delivers …           ┆ delivers s…          │
│ gandalf_michael_corl ┆ Mallory Chung ┆ false       ┆ Downey Jr. continues ┆ downey jr continues  │
│ eone_edwar…          ┆               ┆             ┆ with his …           ┆ with his h…          │
│ epic_stardust_hermio ┆ Anna Camacho  ┆ false       ┆ It's not a great     ┆ it s not a great     │
│ ne_granger…          ┆               ┆             ┆ film, but let…       ┆ film but let …       │
│ ellis_redding_t-800_ ┆ Cheryl Fuller ┆ false       ┆ RECOMMENDED          ┆ recommended          │
│ harry_pott…          ┆               ┆             ┆ "Deliverance" with…  ┆ deliverance with a…  │
└──────────────────────┴───────────────┴─────────────┴──────────────────────┴──────────────────────┘

In [24]:
make_predictions(
    new_data=new_data,
    text_column_name="cleaned_text",  # this is the column name of the text data,
    prediction_column_name="sentiment_predictions",  # Optional custom name
    trained_results=model
)

shape: (13_828, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ movieid      ┆ reviewerName ┆ isTopCritic ┆ reviewText  ┆ cleaned_tex ┆ sentiment_p ┆ confidence │
│ ---          ┆ ---          ┆ ---         ┆ ---         ┆ t           ┆ redictions  ┆ ---        │
│ str          ┆ str          ┆ bool        ┆ str         ┆ ---         ┆ ---         ┆ f64        │
│              ┆              ┆             ┆             ┆ str         ┆ str         ┆            │
╞══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ spectacular_ ┆ Craig        ┆ false       ┆ Cranston    ┆ cranston    ┆ POSITIVE    ┆ 0.746572   │
│ whirlwind_da ┆ Lambert      ┆             ┆ commands    ┆ commands    ┆             ┆            │
│ zzling…      ┆              ┆             ┆ the screen, ┆ the screen  ┆             ┆            │
│              ┆              ┆             ┆ …           ┆ b…          ┆             ┆            │
│ astonish_kat ┆ Sara French  ┆ true        ┆ All good    ┆ all good    ┆ POSITIVE    ┆ 0.92632    │
│ niss_everdee ┆              ┆             ┆ stuff. Rock ┆ stuff rock  ┆             ┆            │
│ n_myri…      ┆              ┆             ┆ delivers …  ┆ delivers s… ┆             ┆            │
│ gandalf_mich ┆ Mallory      ┆ false       ┆ Downey Jr.  ┆ downey jr   ┆ NEGATIVE    ┆ 0.652623   │
│ ael_corleone ┆ Chung        ┆             ┆ continues   ┆ continues   ┆             ┆            │
│ _edwar…      ┆              ┆             ┆ with his …  ┆ with his h… ┆             ┆            │
│ epic_stardus ┆ Anna Camacho ┆ false       ┆ It's not a  ┆ it s not a  ┆ POSITIVE    ┆ 0.923441   │
│ t_hermione_g ┆              ┆             ┆ great film, ┆ great film  ┆             ┆            │
│ ranger…      ┆              ┆             ┆ but let…    ┆ but let …   ┆             ┆            │
│ ellis_reddin ┆ Cheryl       ┆ false       ┆ RECOMMENDED ┆ recommended ┆ POSITIVE    ┆ 0.592365   │
│ g_t-800_harr ┆ Fuller       ┆             ┆ "Deliveranc ┆ deliverance ┆             ┆            │
│ y_pott…      ┆              ┆             ┆ e" with…    ┆ with a…     ┆             ┆            │
│ …            ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …          │
│ katniss_ever ┆ Bryan        ┆ true        ┆ "No one's   ┆ no one s    ┆ NEGATIVE    ┆ 0.831013   │
│ deen_superma ┆ Phillips     ┆             ┆ riding that ┆ riding that ┆             ┆            │
│ n_harr…      ┆              ┆             ┆ loco thi…   ┆ loco thin…  ┆             ┆            │
│ evoke_wonder ┆ Michele      ┆ true        ┆ [A Taste of ┆ has an      ┆ POSITIVE    ┆ 0.790248   │
│ _woman_myria ┆ Tucker       ┆             ┆ Honey] has  ┆ earthy      ┆             ┆            │
│ d_john…      ┆              ┆             ┆ an eart…    ┆ gusto and   ┆             ┆            │
│              ┆              ┆             ┆             ┆ sincer…     ┆             ┆            │
│ miracle_luke ┆ William      ┆ true        ┆ You put up  ┆ you put up  ┆ NEGATIVE    ┆ 0.858885   │
│ _skywalker_d ┆ Holland      ┆             ┆ with lines  ┆ with lines  ┆             ┆            │
│ estiny…      ┆              ┆             ┆ such as …   ┆ such as …   ┆             ┆            │
│ hannibal_lec ┆ Melanie      ┆ false       ┆ It is not   ┆ it is not   ┆ NEGATIVE    ┆ 0.850014   │
│ ter_lara_cro ┆ Sloan        ┆             ┆ that the    ┆ that the    ┆             ┆            │
│ ft           ┆              ┆             ┆ film is     ┆ film is     ┆             ┆            │
│              ┆              ┆             ┆ ste…        ┆ ste…        ┆             ┆            │
│ neo_tony_mon ┆ Robert       ┆ true        ┆ Where Drive ┆ where drive ┆ NEGATIVE    ┆ 0.563638   │
│ tana_vito_co ┆ Faulkner     ┆             ┆ shrewdly    ┆ shrewdly    ┆             ┆            │
│ rleone       ┆              ┆             ┆ mystifies…  ┆ mystifies…  ┆             ┆            │
└──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘