In [1]:

pip install quick-sentiments==0.4.5

Collecting quick-sentiments==0.4.5
  Downloading quick_sentiments-0.4.5-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.23.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (2.4.3)
Requirement already satisfied: pandas>=2.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (3.0.1)
Requirement already satisfied: polars>=0.20.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (1.39.3)
Requirement already satisfied: scipy>=1.9.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (1.17.1)
Requirement already satisfied: scikit-learn>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (1.8.0)
Requirement already satisfied: xgboost>=2.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (3.2.0)
Requirement already satisfied: gensim>=4.3.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (4.4.0)
Requirement already satisfied: nltk==3.8.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (3.8.1)
Requirement already satisfied: spacy>=3.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick-sentiments==0.4.5) (3.8.11)
Requirement already satisfied: click in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.4.5) (8.3.1)
Requirement already satisfied: joblib in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.4.5) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.4.5) (2026.2.28)
Requirement already satisfied: tqdm in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick-sentiments==0.4.5) (4.67.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from gensim>=4.3.3->quick-sentiments==0.4.5) (7.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick-sentiments==0.4.5) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick-sentiments==0.4.5) (2025.3)
Requirement already satisfied: polars-runtime-32==1.39.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from polars>=0.20.0->quick-sentiments==0.4.5) (1.39.3)
Requirement already satisfied: six>=1.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->quick-sentiments==0.4.5) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from scikit-learn>=1.3.0->quick-sentiments==0.4.5) (3.6.0)
Requirement already satisfied: wrapt in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from smart_open>=1.8.1->gensim>=4.3.3->quick-sentiments==0.4.5) (2.1.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (8.3.11)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (2.12.5)
Requirement already satisfied: jinja2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (3.1.6)
Requirement already satisfied: setuptools in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (80.10.2)
Requirement already satisfied: packaging>=20.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick-sentiments==0.4.5) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.4.5) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.4.5) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.4.5) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick-sentiments==0.4.5) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.4.5) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.4.5) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.4.5) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick-sentiments==0.4.5) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick-sentiments==0.4.5) (1.3.3)
Requirement already satisfied: confection<1.1.0,>=0.0.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick-sentiments==0.4.5) (0.1.5)
Requirement already satisfied: colorama in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from tqdm->nltk==3.8.1->quick-sentiments==0.4.5) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy>=3.0.0->quick-sentiments==0.4.5) (0.23.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick-sentiments==0.4.5) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from jinja2->spacy>=3.0.0->quick-sentiments==0.4.5) (3.0.3)
Downloading quick_sentiments-0.4.5-py3-none-any.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ----------------------- ---------------- 1.6/2.6 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 9.8 MB/s  0:00:00
Installing collected packages: quick-sentiments
  Attempting uninstall: quick-sentiments
    Found existing installation: quick-sentiments 0.4.4
    Uninstalling quick-sentiments-0.4.4:
      Successfully uninstalled quick-sentiments-0.4.4
Successfully installed quick-sentiments-0.4.5
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip show quick_sentiments #check for latest version

Name: quick-sentiments
Version: 0.4.5
Summary: Sentiment Analysis pipeline
Home-page: https://github.com/AlabhyaMe/Sentiments-Analysis
Author: Alabhya Dahal
Author-email: Alabhya Dahal <alabhya.dahal@gmail.com>
License: MIT License
Location: C:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages
Requires: gensim, nltk, numpy, pandas, polars, scikit-learn, scipy, spacy, xgboost
Required-by:

WARNING: Package(s) not found: #check, for, latest, version

In [3]:
import polars as pl

# here I have three python script I built to pre_process the data and running the pipeline
# you can find the code in the tools/preprocess.py file
# you can find  the code in the tools/pipeline.py file
# the pre_process function is used to clean the text data, there are various options available, please check the tools/preprocess.py file for details
# the run_pipeline function is used to run the sentimental analysis pipeline, it takes the training data and the vectorizer and machine learning methods as input, and returns the results
from quick_sentiments import pre_process_nltk
from quick_sentiments import pre_process_spacy
from quick_sentiments import run_pipeline
from quick_sentiments import make_predictions

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\meala\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\meala\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

### Training Dataset

Name your data as Train.csv and place it in the Training Data folder. Or you can change the path in the code below.

In [4]:
# keep you training dataset in the training data folder
# this template uses csv files 
# column names can be set in Python but this template does not automatically update the column for the demo 
# however, the function will give you the option to tell column names for the text and label data

df_train = pl.read_csv("demo/training_data/train.csv",encoding='ISO-8859-1') 
print(f"Dataset shape: {df_train.shape[0]} rows and {df_train.shape[1]} columns")

Dataset shape: 162758 rows and 5 columns

### DEMO

In [5]:
df_train.head()
# randomly select only 10% of the data since the dataset is large
#RUN ONLY ONCE
df_train = df_train.sample(fraction=0.25, shuffle=True, seed=42) 
df_train.head(5)

shape: (5, 5)
┌───────────────────────┬──────────────────┬────────────────────┬──────────────────────┬───────────┐
│ movieid               ┆ reviewerName     ┆ isFrequentReviewer ┆ reviewText           ┆ sentiment │
│ ---                   ┆ ---              ┆ ---                ┆ ---                  ┆ ---       │
│ str                   ┆ str              ┆ bool               ┆ str                  ┆ str       │
╞═══════════════════════╪══════════════════╪════════════════════╪══════════════════════╪═══════════╡
│ don_vito_corleone_wil ┆ Jacob Hansen Jr. ┆ true               ┆ An acceptably        ┆ NEGATIVE  │
│ ly_wonka_…            ┆                  ┆                    ┆ mindless sanctua…    ┆           │
│ annie_hall_james_t._k ┆ Manuel Ramirez   ┆ false              ┆ Although many shots  ┆ POSITIVE  │
│ irk_hiccu…            ┆                  ┆                    ┆ are out of…          ┆           │
│ ellis_redding_legend_ ┆ Jose Mccormick   ┆ false              ┆ null                 ┆ NEGATIVE  │
│ forrest_g…            ┆                  ┆                    ┆                      ┆           │
│ infinite_gandalf_the_ ┆ Heidi Wood       ┆ false              ┆ 10 Cloverfield Lane  ┆ POSITIVE  │
│ grey                  ┆                  ┆                    ┆ is an exci…          ┆           │
│ katniss_everdeen_dart ┆ Nicholas Park    ┆ true               ┆ It's funny, fast,    ┆ POSITIVE  │
│ h_vader_n…            ┆                  ┆                    ┆ and charming…        ┆           │
└───────────────────────┴──────────────────┴────────────────────┴──────────────────────┴───────────┘

The dataset is for training. The sentiments are already labeled. This will allow us to train a model that can predict sentiments on new data.

In [6]:
# you can use the pre_process function to clean the text data
response_column = "reviewText" # this is the column name for the text data, feel free to change it to your text column name
sentiment_column = "sentiment" # this is the column name for the sentiment data, feel free to change it to your sentiment column name

In [7]:
# make changes as necessary
# inside the map_elements, add  the parameters [pre_process(x, parameters_to_be_added)] and set it True/False if it differs from the defualt value
# check the tools/preprocess.py file for the parameters and their default values
# some of the parameters are remove_brackets, remove_stopwords, remove_punctuation, remove_numbers, remove_emojis, remove_urls, remove_html_tags, lemmatize, stem, lowercase
df_train = pre_process_nltk(df_train, text_column=response_column, new_column_name="cleaned_text_nltk")

In [8]:
df_train = pre_process_spacy(df_train, text_column=response_column, new_column_name="cleaned_text_spacy")

In [9]:
df_train.head()

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬─────────────┬───────────┬─────────────┬─────────────┐
│ movieid      ┆ reviewerName ┆ isFrequentRe ┆ reviewText  ┆ sentiment ┆ cleaned_tex ┆ cleaned_tex │
│ ---          ┆ ---          ┆ viewer       ┆ ---         ┆ ---       ┆ t_nltk      ┆ t_spacy     │
│ str          ┆ str          ┆ ---          ┆ str         ┆ str       ┆ ---         ┆ ---         │
│              ┆              ┆ bool         ┆             ┆           ┆ str         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══════════╪═════════════╪═════════════╡
│ don_vito_cor ┆ Jacob Hansen ┆ true         ┆ An          ┆ NEGATIVE  ┆ an          ┆ an          │
│ leone_willy_ ┆ Jr.          ┆              ┆ acceptably  ┆           ┆ acceptably  ┆ acceptably  │
│ wonka_…      ┆              ┆              ┆ mindless    ┆           ┆ mindless    ┆ mindless    │
│              ┆              ┆              ┆ sanctua…    ┆           ┆ sanctua…    ┆ sanctua…    │
│ annie_hall_j ┆ Manuel       ┆ false        ┆ Although    ┆ POSITIVE  ┆ although    ┆ although    │
│ ames_t._kirk ┆ Ramirez      ┆              ┆ many shots  ┆           ┆ many shots  ┆ many shots  │
│ _hiccu…      ┆              ┆              ┆ are out of… ┆           ┆ are out of… ┆ are out of… │
│ ellis_reddin ┆ Jose         ┆ false        ┆ null        ┆ NEGATIVE  ┆             ┆             │
│ g_legend_for ┆ Mccormick    ┆              ┆             ┆           ┆             ┆             │
│ rest_g…      ┆              ┆              ┆             ┆           ┆             ┆             │
│ infinite_gan ┆ Heidi Wood   ┆ false        ┆ 10          ┆ POSITIVE  ┆ cloverfield ┆ cloverfield │
│ dalf_the_gre ┆              ┆              ┆ Cloverfield ┆           ┆ lane is an  ┆ lane is an  │
│ y            ┆              ┆              ┆ Lane is an  ┆           ┆ excitin…    ┆ excitin…    │
│              ┆              ┆              ┆ exci…       ┆           ┆             ┆             │
│ katniss_ever ┆ Nicholas     ┆ true         ┆ It's funny, ┆ POSITIVE  ┆ it s funny  ┆ it s funny  │
│ deen_darth_v ┆ Park         ┆              ┆ fast, and   ┆           ┆ fast and    ┆ fast and    │
│ ader_n…      ┆              ┆              ┆ charming…   ┆           ┆ charming    ┆ charming    │
└──────────────┴──────────────┴──────────────┴─────────────┴───────────┴─────────────┴─────────────┘

In [ ]:
#### in this template, there are five+ text representation / vectorizer methods available 
#### in the function run_pipeline (in python cell below), we shall make use of this, write the words inside [ ] for the methods you want to use
#### 1. Bag of Words [BOW] 
#### 2. Term Frequency [tf]
#### 3. TF -IDF    [tfidf]
#### 4. Word Embedding using Word2Vec (you can use other packages with slight changes) [wv] 
         # Word Embedding uses defualt 300 values; this will take some time to run
#### 5. Glove (you can use other packages with slight changes) [glove_25,glove_50, glove_100, gl0ve_200]

In [ ]:
#### in this template, there are also five machine learning methods that can be used
#### 1. Logistic Regression [logit]
#### 2. Random forest (recommended) (rf)
#### 3. XGBoosting  [XGB](word embedding and XGBoost may take long time to complete, combination of both is not recommended in local machine)
#### 4. Naive Bayes [nb]
#### 5. Neural Network [nn] (this will take some time to run, and may run out of memory if the dataset is large, so be careful when using this method)

In [11]:
pip install quick_sentiments[dl]

Requirement already satisfied: quick_sentiments[dl] in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (0.4.5)
Requirement already satisfied: numpy>=1.23.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (2.4.3)
Requirement already satisfied: pandas>=2.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (3.0.1)
Requirement already satisfied: polars>=0.20.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (1.39.3)
Requirement already satisfied: scipy>=1.9.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (1.17.1)
Requirement already satisfied: scikit-learn>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (1.8.0)
Requirement already satisfied: xgboost>=2.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (3.2.0)
Requirement already satisfied: gensim>=4.3.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (4.4.0)
Requirement already satisfied: nltk==3.8.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (3.8.1)
Requirement already satisfied: spacy>=3.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from quick_sentiments[dl]) (3.8.11)
Collecting tensorflow>=2.13.0 (from quick_sentiments[dl])
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting scikeras>=0.12.0 (from quick_sentiments[dl])
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: click in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick_sentiments[dl]) (8.3.1)
Requirement already satisfied: joblib in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick_sentiments[dl]) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick_sentiments[dl]) (2026.2.28)
Requirement already satisfied: tqdm in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from nltk==3.8.1->quick_sentiments[dl]) (4.67.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from gensim>=4.3.3->quick_sentiments[dl]) (7.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick_sentiments[dl]) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pandas>=2.0.0->quick_sentiments[dl]) (2025.3)
Requirement already satisfied: polars-runtime-32==1.39.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from polars>=0.20.0->quick_sentiments[dl]) (1.39.3)
Requirement already satisfied: six>=1.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->quick_sentiments[dl]) (1.17.0)
Collecting keras>=3.2.0 (from scikeras>=0.12.0->quick_sentiments[dl])
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Collecting absl-py (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: rich in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl]) (14.3.3)
Collecting namex (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting h5py (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Downloading h5py-3.16.0-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Collecting optree (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Downloading optree-0.19.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Collecting ml-dtypes (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: packaging in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl]) (25.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from scikit-learn>=1.3.0->quick_sentiments[dl]) (3.6.0)
Requirement already satisfied: wrapt in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from smart_open>=1.8.1->gensim>=4.3.3->quick_sentiments[dl]) (2.1.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (8.3.11)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (2.12.5)
Requirement already satisfied: jinja2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (3.1.6)
Requirement already satisfied: setuptools in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from spacy>=3.0.0->quick_sentiments[dl]) (80.10.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick_sentiments[dl]) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick_sentiments[dl]) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick_sentiments[dl]) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.0->quick_sentiments[dl]) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick_sentiments[dl]) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick_sentiments[dl]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick_sentiments[dl]) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=3.0.0->quick_sentiments[dl]) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick_sentiments[dl]) (1.3.3)
Requirement already satisfied: confection<1.1.0,>=0.0.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy>=3.0.0->quick_sentiments[dl]) (0.1.5)
Requirement already satisfied: colorama in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from tqdm->nltk==3.8.1->quick_sentiments[dl]) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick_sentiments[dl]) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy>=3.0.0->quick_sentiments[dl]) (0.23.0)
Collecting astunparse>=1.6.0 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting termcolor>=1.1.0 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow>=2.13.0->quick_sentiments[dl])
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting h5py (from keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl])
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from astunparse>=1.6.0->tensorflow>=2.13.0->quick_sentiments[dl]) (0.46.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick_sentiments[dl]) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy>=3.0.0->quick_sentiments[dl]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich->keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from rich->keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras>=0.12.0->quick_sentiments[dl]) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\meala\anaconda3\envs\quicksentiment\Lib\site-packages (from jinja2->spacy>=3.0.0->quick_sentiments[dl]) (3.0.3)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Downloading keras-3.13.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 13.7 MB/s  0:00:00
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
    --------------------------------------- 5.0/351.2 MB 24.3 MB/s eta 0:00:15
   - -------------------------------------- 10.0/351.2 MB 23.5 MB/s eta 0:00:15
   - -------------------------------------- 15.2/351.2 MB 24.0 MB/s eta 0:00:14
   -- ------------------------------------- 19.7/351.2 MB 23.4 MB/s eta 0:00:15
   -- ------------------------------------- 25.2/351.2 MB 23.9 MB/s eta 0:00:14
   --- ------------------------------------ 30.7/351.2 MB 24.2 MB/s eta 0:00:14
   ---- ----------------------------------- 36.2/351.2 MB 24.4 MB/s eta 0:00:13
   ---- ----------------------------------- 41.4/351.2 MB 24.3 MB/s eta 0:00:13
   ----- ---------------------------------- 46.9/351.2 MB 24.5 MB/s eta 0:00:13
   ------ --------------------------------- 53.0/351.2 MB 24.8 MB/s eta 0:00:13
   ------ --------------------------------- 57.4/351.2 MB 24.4 MB/s eta 0:00:13
   ------- -------------------------------- 63.4/351.2 MB 24.9 MB/s eta 0:00:12
   ------- -------------------------------- 69.2/351.2 MB 25.1 MB/s eta 0:00:12
   -------- ------------------------------- 73.9/351.2 MB 24.8 MB/s eta 0:00:12
   --------- ------------------------------ 79.7/351.2 MB 24.9 MB/s eta 0:00:11
   --------- ------------------------------ 84.9/351.2 MB 25.0 MB/s eta 0:00:11
   ---------- ----------------------------- 89.9/351.2 MB 25.0 MB/s eta 0:00:11
   ---------- ----------------------------- 94.4/351.2 MB 24.8 MB/s eta 0:00:11
   ----------- ---------------------------- 99.6/351.2 MB 24.8 MB/s eta 0:00:11
   ----------- --------------------------- 104.6/351.2 MB 24.7 MB/s eta 0:00:10
   ------------ -------------------------- 109.8/351.2 MB 24.7 MB/s eta 0:00:10
   ------------ -------------------------- 115.3/351.2 MB 24.7 MB/s eta 0:00:10
   ------------- ------------------------- 119.3/351.2 MB 24.5 MB/s eta 0:00:10
   ------------- ------------------------- 124.5/351.2 MB 24.5 MB/s eta 0:00:10
   -------------- ------------------------ 128.2/351.2 MB 24.3 MB/s eta 0:00:10
   -------------- ------------------------ 132.6/351.2 MB 24.1 MB/s eta 0:00:10
   --------------- ----------------------- 138.1/351.2 MB 24.2 MB/s eta 0:00:09
   --------------- ----------------------- 141.8/351.2 MB 24.0 MB/s eta 0:00:09
   ---------------- ---------------------- 146.5/351.2 MB 23.9 MB/s eta 0:00:09
   ---------------- ---------------------- 149.7/351.2 MB 23.6 MB/s eta 0:00:09
   ----------------- --------------------- 154.1/351.2 MB 23.5 MB/s eta 0:00:09
   ----------------- --------------------- 158.9/351.2 MB 23.5 MB/s eta 0:00:09
   ------------------ -------------------- 163.3/351.2 MB 23.4 MB/s eta 0:00:09
   ------------------ -------------------- 168.3/351.2 MB 23.3 MB/s eta 0:00:08
   ------------------- ------------------- 171.2/351.2 MB 23.2 MB/s eta 0:00:08
   ------------------- ------------------- 174.6/351.2 MB 22.8 MB/s eta 0:00:08
   ------------------- ------------------- 179.3/351.2 MB 22.8 MB/s eta 0:00:08
   -------------------- ------------------ 182.7/351.2 MB 22.7 MB/s eta 0:00:08
   -------------------- ------------------ 184.8/351.2 MB 22.4 MB/s eta 0:00:08
   -------------------- ------------------ 186.4/351.2 MB 22.0 MB/s eta 0:00:08
   --------------------- ----------------- 191.4/351.2 MB 22.0 MB/s eta 0:00:08
   --------------------- ----------------- 195.6/351.2 MB 21.9 MB/s eta 0:00:08
   ---------------------- ---------------- 199.5/351.2 MB 21.8 MB/s eta 0:00:07
   ---------------------- ---------------- 202.9/351.2 MB 21.7 MB/s eta 0:00:07
   ---------------------- ---------------- 206.6/351.2 MB 21.6 MB/s eta 0:00:07
   ----------------------- --------------- 210.5/351.2 MB 21.6 MB/s eta 0:00:07
   ----------------------- --------------- 213.4/351.2 MB 21.4 MB/s eta 0:00:07
   ----------------------- --------------- 216.0/351.2 MB 21.2 MB/s eta 0:00:07
   ------------------------ -------------- 219.9/351.2 MB 21.1 MB/s eta 0:00:07
   ------------------------ -------------- 223.9/351.2 MB 21.1 MB/s eta 0:00:07
   ------------------------- ------------- 227.5/351.2 MB 21.0 MB/s eta 0:00:06
   ------------------------- ------------- 230.2/351.2 MB 20.9 MB/s eta 0:00:06
   ------------------------- ------------- 232.8/351.2 MB 20.7 MB/s eta 0:00:06
   -------------------------- ------------ 235.9/351.2 MB 20.6 MB/s eta 0:00:06
   -------------------------- ------------ 239.3/351.2 MB 20.5 MB/s eta 0:00:06
   -------------------------- ------------ 242.0/351.2 MB 20.4 MB/s eta 0:00:06
   --------------------------- ----------- 245.4/351.2 MB 20.3 MB/s eta 0:00:06
   --------------------------- ----------- 247.7/351.2 MB 20.1 MB/s eta 0:00:06
   --------------------------- ----------- 248.8/351.2 MB 19.9 MB/s eta 0:00:06
   --------------------------- ----------- 249.8/351.2 MB 19.6 MB/s eta 0:00:06
   --------------------------- ----------- 251.7/351.2 MB 19.4 MB/s eta 0:00:06
   ---------------------------- ---------- 253.5/351.2 MB 19.2 MB/s eta 0:00:06
   ---------------------------- ---------- 255.1/351.2 MB 19.1 MB/s eta 0:00:06
   ---------------------------- ---------- 256.1/351.2 MB 19.0 MB/s eta 0:00:06
   ---------------------------- ---------- 257.9/351.2 MB 18.7 MB/s eta 0:00:05
   ---------------------------- ---------- 260.3/351.2 MB 18.6 MB/s eta 0:00:05
   ----------------------------- --------- 262.1/351.2 MB 18.4 MB/s eta 0:00:05
   ----------------------------- --------- 264.0/351.2 MB 18.3 MB/s eta 0:00:05
   ----------------------------- --------- 266.9/351.2 MB 18.1 MB/s eta 0:00:05
   ----------------------------- --------- 268.4/351.2 MB 18.0 MB/s eta 0:00:05
   ------------------------------ -------- 271.1/351.2 MB 17.8 MB/s eta 0:00:05
   ------------------------------ -------- 274.2/351.2 MB 17.7 MB/s eta 0:00:05
   ------------------------------ -------- 277.9/351.2 MB 17.7 MB/s eta 0:00:05
   ------------------------------- ------- 281.8/351.2 MB 17.6 MB/s eta 0:00:04
   ------------------------------- ------- 285.5/351.2 MB 17.5 MB/s eta 0:00:04
   -------------------------------- ------ 288.6/351.2 MB 17.5 MB/s eta 0:00:04
   -------------------------------- ------ 292.3/351.2 MB 17.4 MB/s eta 0:00:04
   -------------------------------- ------ 293.9/351.2 MB 17.3 MB/s eta 0:00:04
   -------------------------------- ------ 293.9/351.2 MB 17.3 MB/s eta 0:00:04
   --------------------------------- ----- 297.5/351.2 MB 16.9 MB/s eta 0:00:04
   --------------------------------- ----- 299.6/351.2 MB 16.7 MB/s eta 0:00:04
   --------------------------------- ----- 301.7/351.2 MB 16.6 MB/s eta 0:00:03
   --------------------------------- ----- 304.1/351.2 MB 16.5 MB/s eta 0:00:03
   --------------------------------- ----- 305.9/351.2 MB 16.3 MB/s eta 0:00:03
   ---------------------------------- ---- 308.0/351.2 MB 16.2 MB/s eta 0:00:03
   ---------------------------------- ---- 309.9/351.2 MB 16.1 MB/s eta 0:00:03

In [ ]:
# this is the example of how to use the function
# you can change the vectorizer_name and model_name to the ones you want to use
# for now we will use word embedding and logistic regression
# write the name of your columns in the text_column_name and sentiment_column_name
# the text_column_name is the column name of the text data, and sentiment_column_name is

# run_pipeline function will return the dataframe with the vectorized text, vectorizer used  and the model
# it will also print the results of the model, including the accuracy and F1 score
# note, even without hyperparameter tuning, the model is getting over 70% accuracy in my test
# there may not be a need to perform hyperparameter tuning, but you can set perform_tuning to True if you want to do that

model = run_pipeline(
    vectorizer_name="wv", # BOW, tf, tfidf, wv,  glove_25,glove_50, glove_100, gl0ve_200,
    model_name="tf", # logit, rf, XGB, nb, nn, tf for tensorflow models .#XGB takes long time, can not recommend using it on normal case
    df=df_train,
    text_column_name="cleaned_text_nltk",  # this is the column name of the text data, 
    sentiment_column_name = "sentiment",
    perform_tuning = True, # make this true if you want to perform hyperparameter tuning, it will take longer time and 
                            # may run out of memory if the dataset is large,
    random_state=259
)

# missing values in the text data will be removed

--- Running Pipeline for Wv + Tf ---
No missing values (None) found in text or sentiment columns. Proceeding with all rows.
Labels encoded: Original -> ['NEGATIVE' 'POSITIVE'], Encoded -> [0 1]
1. Splitting data into train/test...
2. Vectorizing  dataset (X)...
Using already loaded Word2Vec model.
Transforming test data using loaded Word2Vec model...
3. Training and predicting...
   - Building TF Model: Input Features = 300, Output Classes = 2
   - Training TensorFlow model with default parameters...
Epoch 1/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7444 - loss: 0.5026
Epoch 2/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7666 - loss: 0.4728
Epoch 3/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7728 - loss: 0.4638
Epoch 4/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7760 - loss: 0.4573
Epoch 5/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7808 - loss: 0.4511
Epoch 6/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7848 - loss: 0.4448
Epoch 7/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7886 - loss: 0.4378
Epoch 8/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7938 - loss: 0.4313
Epoch 9/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7954 - loss: 0.4243
Epoch 10/10
1018/1018 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7992 - loss: 0.4182
   - Generating predictions...
4. Evaluating model...

Classification Report:
              precision    recall  f1-score   support

    NEGATIVE       0.68      0.59      0.63      2658
    POSITIVE       0.81      0.87      0.84      5480

    accuracy                           0.78      8138
   macro avg       0.75      0.73      0.74      8138
weighted avg       0.77      0.78      0.77      8138

True labels distribution: Counter({np.int64(1): 5480, np.int64(0): 2658})
Predicted labels distribution: Counter({np.int64(1): 5833, np.int64(0): 2305})

In [18]:
## the model is a dictionary that contains the results of the model, including the accuracy and F1 score

# you can access the results using the keys of the dictionary
print("Vectorizer used: ", model["vectorizer_name"])
print("Model used: ", model["model_object"])
print("Accuracy: ", model["accuracy"])

Vectorizer used:  wv
Model used:  KerasClassifier(
	model=<function build_keras_model at 0x000001BE91E1DEE0>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=32
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=10
	model__input_dim=300
	model__num_classes=2
	class_weight=None
)
Accuracy:  0.7762349471614647

### New Dataset for prediction
You can use the same format as the training dataset, but ensure that it contains the "Response" column for text data. The "Sentiment" column is optional for prediction datasets, as it will be generated by the model.
Make sure the dataset is saved in the "New Data" folder and is in CSV format.

In [ ]:
new_data = pl.read_csv("demo/new_data/test.csv",encoding='ISO-8859-1') #keep your file here
print(new_data.shape)
new_data= new_data.sample(fraction=0.25, shuffle=True, seed=42)
print(new_data.shape)

In [ ]:
new_data = pre_process_nltk(new_data, text_column=response_column, new_column_name="cleaned_text")
new_data.head()

In [ ]:
make_predictions(
    new_data=new_data,
    text_column_name="cleaned_text",  # this is the column name of the text data,
    prediction_column_name="sentiment_predictions",  # Optional custom name
    trained_results=model
)